### ISSUE TITLE
remove notebooks from CI

### ISSUE THREAD

**Issue by giovp** [scverse/squidpy_notebooks#112]
- [x] convert all python files in `tutorials` into ipynb
- [x] run all new notebooks
- [x] move all new notebooks into docs/source/tutorials (create this new folder tutorials)
- [x] copy external_tutorials into new folder tutorials
- [x] in `tutorials.rst` add correct indexing for the documentation.
- [x] update tutorial.rst also in `squidpy`

**Comment by LLehner** [comment]
Completed in #113.
