### ISSUE TITLE
Issue with Xenium Tutorial Notebook

### ISSUE THREAD

**Issue by albert239825** [scverse/squidpy_notebooks#135]
https://github.com/scverse/squidpy_notebooks/blob/79257ebbcff71260d752eae9a00a5ea36b8542ee/tutorials/tutorial_xenium.ipynb

I believe `xenium.write(zarr_path)` should be `sdata.write(zarr_path)`. I was running it and the current iteration says xenium has no function write. Please correct me if I am mistaken. Thanks!

**Comment by ilan-gold** [comment]
Similarly, there was a broken link which needs to be looked at: https://github.com/scverse/squidpy_notebooks/pull/138

**Comment by wlason** [comment]
Hi @LLehner! Thank you for updating the tutorial with `SpatialData`, that is super helpful! I also came here to tell you about the typo, it should be `sdata.write()` not `xenium.write()` - I ran the whole tutorial.

**Comment by LLehner** [comment]
Hi @albert239825, you are correct, this is a typo! Also thanks @wlason for spotting the other typo, will update the notebook tomorrow!
